### ISSUE TITLE
Infinite query type issues

### ISSUE THREAD

**Issue by filipjakov** [kubb-labs/kubb#1864]
### What version of `kubb` is running?

3.18.2

### What kind of platform do you use?

MacOS

### Your `kubb.config.ts` config file?

```typescript
not relevant
```

### Swagger/OpenAPI file?

```bash

```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON

```

### What steps can reproduce the bug?

I have 2 issues with the generated types:

1. infinite query `page` param type error. Example:

```tsx
export function officeControllerInfiniteQueryOptions(
	params: OfficeControllerQueryParams,
	config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
	const queryKey = officeControllerInfiniteQueryKey(params);
	return infiniteQueryOptions<
		ResponseConfig<OfficeControllerQueryResponse>,
		ResponseErrorConfig<OfficeController500>,
		ResponseConfig<OfficeControllerQueryResponse>,
		typeof queryKey,
		number
	>({
		enabled: !!params,
		queryKey,
		queryFn: async ({ signal, pageParam }) => {
			config.signal = signal;

			if (params) {
				params['page'] =
					pageParam as unknown as OfficeControllerQueryParams['page']; // <-- ERRORS
			}
			return officeController(params, config);
		},
		initialPageParam: 1,
		getNextPageParam: (lastPage, _allPages, lastPageParam) =>
			Array.isArray(lastPage.data) && lastPage.data.length === 0 ? undefined : lastPageParam + 1,
		getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
			firstPageParam <= 1 ? undefined : firstPageParam - 1,
	});
}
```

where i get the following error:

```tsx
Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.ts(2322)
```

for the line denoted with ERRORS above. 

2. The generated infinite query hook contains a generic in the function definition which is not being used, erroring in TS as well.

```tsx
export function useOfficeControllerInfinite<
	TData = InfiniteData<ResponseConfig<OfficeControllerQueryResponse>>,
	TQueryData = ResponseConfig<OfficeControllerQueryResponse>, // <-- ERROR
	TQueryKey extends QueryKey = OfficeControllerInfiniteQueryKey,
>(
```

I get the following error:

```tsx
'TQueryData' is declared but its value is never read.ts(6133)
```

### How often does this bug happen?

Every time

### What is the expected behaviour?

No Typescript errors.

### Additional information

Typescript configuration in playground: https://codesandbox.io/p/sandbox/ls92td

**Comment by komali2** [comment]
I'm also suddenly getting errors with infinite queries on the latest version, specifically with getNextPageParam's lastPageParam type being `unknown` which is new. I've just started investigating.

**Comment by stijnvanhulle** [comment]
@filipjakov @komali2 Fixed with `v3.18.3`

**Comment by filipjakov** [comment]
hey @stijnvanhulle, thanks for checking it out

Used 3.18.3, but some new errors popped up:

1. These lines seem like new additions:

```tsx
			if (!params) {
				params = {};
			}
```

and I get `Property 'X' is missing in type '{}' but required in type 'Interface'` ->  empty object does not satisfy the constraints defined by `params` interface

2. First error from the original issue (above), still not fixed.


```tsx
Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

<img width="648" height="169" alt="Image" src="https://github.com/user-attachments/assets/f4984c31-89f2-4a4d-be9d-3c25af0dc7c8" />


3. Regarding unsued `TQueryData` (second issue from the original report), now I'm getting two new errors:

- `Type 'TQueryData' does not satisfy the constraint 'QueryKey'`

```tsx
Conversion of type 'readonly [{ readonly url: "/brand-api/v1/office/orders"; }, ...OfficeControllerGetOrdersQueryParams[]] | (TQueryData & {})' to type 'TQueryKey' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'TQueryKey' could be instantiated with an arbitrary type which could be unrelated to 'readonly [{ readonly url: "/brand-api/v1/office/orders"; }, ...OfficeControllerGetOrdersQueryParams[]] | (TQueryData & {})'
```

<img width="672" height="688" alt="Image" src="https://github.com/user-attachments/assets/ee4b62d1-a422-4687-9cde-75b12e9fde4f" />


Think this issue can be reopened. Let me know if I can provide more info

**Comment by gentrith44belt** [comment]
I upgraded to 3.18.3, im getting exactly the same issues!
Im kinda blocked because the old versions are not working anymore I guess, Im getting an error "stringWidth of undefined"!


@stijnvanhulle do you have any workaround for this ?

Update: v3.16.3 seems to be working for me!

**Comment by filipjakov** [comment]
hey @stijnvanhulle, any news on this one?

**Comment by humarkx** [comment]
#1890 Should fix this.

I am using this patch, works correctly with all the InfiniteQueries

**Comment by vitalygashkov** [comment]
> hey [@stijnvanhulle](https://github.com/stijnvanhulle), thanks for checking it out
> 
> Used 3.18.3, but some new errors popped up:
> 
> 1. These lines seem like new additions:
> 
> 			if (!params) {
> 				params = {};
> 			}
> and I get `Property 'X' is missing in type '{}' but required in type 'Interface'` -> empty object does not satisfy the constraints defined by `params` interface
> 

I'm using v4.0.2. 
Same TypeScript error (`Type '{}' is missing the following properties from type ...`) for infinite query in this part of code:
```ts
if (!params) {
  params = {};
}
```

**Comment by humarkx** [comment]
@vitalygashkov already addressed on the PR

**Comment by filipjakov** [comment]
Hey @stijnvanhulle @humarkx , still not fixed after upgrading to 4.1.2.

The issues are now (image below, all realted to Infinite hook generation):

1. `Type 'TPageParam' does not satisfy the constraint 'QueryKey'`
2. `Types of property 'queryKey' are incompatible.`
3.  `Conversion of type 'readonly [{ readonly url: "/brand-api/v1/office/users"; }, ...OfficeControllerGetUsersQueryParams[]] | (TPageParam & {})' to type 'TQueryKey' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
`

<img width="831" height="834" alt="Image" src="https://github.com/user-attachments/assets/6e0a6655-738e-4784-b58d-28d83812f764" />

Typescript configuration same as in the sandbox linked above (first message).
Let me know if you need any more info, but think the issue can be reopened.

**Comment by filipjakov** [comment]
hey @stijnvanhulle the above still persists on 4.3.0

should i open another issue?
